export type EventSource = "rosmolodez" | "roscongress" | "unidoka" | "rovno";

export type EventType =
  | "IT"
  | "Business"
  | "Chill"
  | "Art"
  | "Design"
  | "Diplomacy"
  | "Construction"
  | "Science"
  | "Media"
  | "Sport";

export interface EventItem {
  id: string;
  title: string;
  description: string;
  source: EventSource;
  /** Display name shown in filters and cards. */
  organizer: string;
  type: EventType;
  country: string;
  /** Inclusive age range. Missing = no restriction. */
  ageMin?: number;
  ageMax?: number;
  /** True if the event can be registered for right now. */
  registrationOpen: boolean;
  startsAt: string;
  endsAt?: string;
  location?: string;
  url?: string;
  tags?: string[];
  prize?: string;
}

export const TYPE_LABEL: Record<EventType, string> = {
  IT: "IT",
  Business: "Бизнес",
  Chill: "Досуг",
  Art: "Искусство",
  Design: "Дизайн",
  Diplomacy: "Дипломатия",
  Construction: "Строительство",
  Science: "Наука",
  Media: "Медиа",
  Sport: "Спорт",
};

export const ALL_TYPES: EventType[] = Object.keys(TYPE_LABEL) as EventType[];

export const SEED_EVENTS: EventItem[] = [
  // --- Росмолодёжь ---------------------------------------------------
  {
    id: "rm-territoriya-2026",
    title: "Форум «Территория смыслов»",
    description:
      "Главная молодёжная образовательная площадка страны. Смены по IT, дизайну, медиа и предпринимательству.",
    source: "rosmolodez",
    organizer: "Росмолодёжь",
    type: "Business",
    country: "Россия",
    ageMin: 18,
    ageMax: 35,
    registrationOpen: true,
    startsAt: "2026-10-05",
    endsAt: "2026-10-12",
    location: "Сенеж, Московская область",
    url: "https://rosmolodez.gov.ru",
    tags: ["форум", "образование"],
  },
  {
    id: "rm-tvoy-hod-2026",
    title: "Конкурс «Твой Ход» — третий сезон",
    description:
      "Всероссийский конкурс для студентов: индивидуальные и командные треки, гранты и стажировки.",
    source: "rosmolodez",
    organizer: "Росмолодёжь",
    type: "Business",
    country: "Россия",
    ageMin: 16,
    ageMax: 30,
    registrationOpen: true,
    startsAt: "2026-10-01",
    endsAt: "2027-06-30",
    url: "https://tvoyhod.online",
    tags: ["конкурс", "грант"],
    prize: "до 1 000 000 ₽",
  },
  {
    id: "rm-evraziya-2026",
    title: "Международный форум «Евразия Global»",
    description: "Площадка для общения молодёжи из России и стран ЕАЭС.",
    source: "rosmolodez",
    organizer: "Росмолодёжь",
    type: "Diplomacy",
    country: "Россия",
    ageMin: 18,
    ageMax: 35,
    registrationOpen: false,
    startsAt: "2026-09-25",
    endsAt: "2026-09-30",
    location: "Оренбург",
    url: "https://rosmolodez.gov.ru",
    tags: ["форум", "международное"],
  },
  {
    id: "rm-grants-wave-3",
    title: "Грантовый конкурс Росмолодёжи — III волна",
    description:
      "Приём заявок на гранты для молодёжных проектов. До 1.5 млн рублей на команду.",
    source: "rosmolodez",
    organizer: "Росмолодёжь",
    type: "Business",
    country: "Россия",
    ageMin: 14,
    ageMax: 35,
    registrationOpen: true,
    startsAt: "2026-11-01",
    endsAt: "2026-12-15",
    url: "https://myrosmol.ru",
    tags: ["грант"],
  },
  {
    id: "rm-baikal-2026",
    title: "Молодёжный форум «Байкал»",
    description:
      "Образовательный форум на Байкале: экология, урбанистика, креативные индустрии.",
    source: "rosmolodez",
    organizer: "Росмолодёжь",
    type: "Science",
    country: "Россия",
    ageMin: 18,
    ageMax: 35,
    registrationOpen: false,
    startsAt: "2026-11-15",
    endsAt: "2026-11-20",
    location: "Иркутская область",
    tags: ["форум"],
  },
  {
    id: "rm-ostrova-2027",
    title: "Молодёжный форум «ОстроVа»",
    description: "Тихоокеанский форум: карьера, предпринимательство, медиа.",
    source: "rosmolodez",
    organizer: "Росмолодёжь",
    type: "Media",
    country: "Россия",
    ageMin: 18,
    ageMax: 35,
    registrationOpen: false,
    startsAt: "2027-07-10",
    endsAt: "2027-07-18",
    location: "Сахалин",
    tags: ["форум"],
  },
  {
    id: "rm-utro-2027",
    title: "Форум «УТРО»",
    description: "Образовательный форум Уральского федерального округа.",
    source: "rosmolodez",
    organizer: "Росмолодёжь",
    type: "Chill",
    country: "Россия",
    ageMin: 16,
    ageMax: 35,
    registrationOpen: false,
    startsAt: "2027-06-20",
    endsAt: "2027-06-26",
    location: "Челябинская область",
    tags: ["форум"],
  },

  // --- Росконгресс ---------------------------------------------------
  {
    id: "rc-hack-transport-2026",
    title: "Хакатон Московского Транспорта",
    description:
      "Геймификация ВСМ, цифровые сервисы для пассажиров. Трек для продуктовых команд.",
    source: "roscongress",
    organizer: "Росконгресс",
    type: "IT",
    country: "Россия",
    ageMin: 18,
    ageMax: 35,
    registrationOpen: true,
    startsAt: "2026-09-25",
    endsAt: "2026-10-03",
    location: "Москва",
    url: "https://roscongress.org",
    tags: ["хакатон", "транспорт"],
    prize: "500 000 ₽",
  },
  {
    id: "rc-ren-2026",
    title: "Российская энергетическая неделя",
    description: "Международный форум по энергетике: нефть, газ, ВИЭ, водород.",
    source: "roscongress",
    organizer: "Росконгресс",
    type: "Business",
    country: "Россия",
    ageMin: 18,
    registrationOpen: true,
    startsAt: "2026-10-15",
    endsAt: "2026-10-17",
    location: "Москва, Манеж",
    url: "https://rusenergyweek.com",
    tags: ["форум", "энергетика"],
  },
  {
    id: "rc-healthy-society-2026",
    title: "Форум «Здоровое общество»",
    description: "Демография, медицина, ЗОЖ. Ключевая площадка соцповестки.",
    source: "roscongress",
    organizer: "Росконгресс",
    type: "Science",
    country: "Россия",
    ageMin: 18,
    registrationOpen: false,
    startsAt: "2026-10-22",
    endsAt: "2026-10-23",
    location: "Москва",
    url: "https://roscongress.org",
    tags: ["форум", "здоровье"],
  },
  {
    id: "rc-microelectronics-2026",
    title: "Форум «Микроэлектроника»",
    description:
      "Технологический форум о производстве чипов и электронной компонентной базы.",
    source: "roscongress",
    organizer: "Росконгресс",
    type: "IT",
    country: "Россия",
    ageMin: 18,
    registrationOpen: true,
    startsAt: "2026-11-05",
    endsAt: "2026-11-07",
    location: "Сочи, Сириус",
    tags: ["форум", "hardware"],
  },
  {
    id: "rc-made-in-russia-2026",
    title: "Форум «Сделано в России»",
    description: "Экспорт, промышленность, импортозамещение.",
    source: "roscongress",
    organizer: "Росконгресс",
    type: "Business",
    country: "Россия",
    ageMin: 18,
    registrationOpen: false,
    startsAt: "2026-11-19",
    endsAt: "2026-11-20",
    location: "Москва",
    tags: ["форум", "экспорт"],
  },
  {
    id: "rc-creative-week-2026",
    title: "Российская креативная неделя",
    description:
      "Фестиваль креативных индустрий: дизайн, кино, музыка, мода, геймдев.",
    source: "roscongress",
    organizer: "Росконгресс",
    type: "Design",
    country: "Россия",
    ageMin: 16,
    registrationOpen: true,
    startsAt: "2026-12-02",
    endsAt: "2026-12-05",
    location: "Москва",
    url: "https://creativeweek.ru",
    tags: ["фестиваль", "креатив"],
  },
  {
    id: "rc-invest-sochi-2027",
    title: "Российский инвестиционный форум",
    description: "Инвестиции, регионы, инфраструктурные проекты.",
    source: "roscongress",
    organizer: "Росконгресс",
    type: "Business",
    country: "Россия",
    ageMin: 21,
    registrationOpen: false,
    startsAt: "2027-02-15",
    endsAt: "2027-02-17",
    location: "Сочи",
    url: "https://roscongress.org",
    tags: ["форум", "инвестиции"],
  },
  {
    id: "rc-pmef-2027",
    title: "Петербургский международный экономический форум (ПМЭФ)",
    description: "Главное деловое событие страны.",
    source: "roscongress",
    organizer: "Росконгресс",
    type: "Business",
    country: "Россия",
    ageMin: 21,
    registrationOpen: false,
    startsAt: "2027-06-02",
    endsAt: "2027-06-05",
    location: "Санкт-Петербург, Экспофорум",
    url: "https://forumspb.com",
    tags: ["форум", "экономика"],
  },
  {
    id: "rc-vef-2027",
    title: "Восточный экономический форум (ВЭФ)",
    description: "Развитие Дальнего Востока, сотрудничество со странами АТР.",
    source: "roscongress",
    organizer: "Росконгресс",
    type: "Diplomacy",
    country: "Россия",
    ageMin: 18,
    registrationOpen: false,
    startsAt: "2027-09-03",
    endsAt: "2027-09-06",
    location: "Владивосток",
    url: "https://forumvostok.ru",
    tags: ["форум", "атр"],
  },

  // --- Unidoka / Rovno.dev internal -----------------------------------
  {
    id: "un-cortex-challenge-2026",
    title: "Cortex Challenge 2026",
    description:
      "Соревнование по BI и аналитике данных. Командный трек, реальные бизнес-кейсы.",
    source: "unidoka",
    organizer: "Унидока",
    type: "IT",
    country: "Россия",
    ageMin: 16,
    ageMax: 30,
    registrationOpen: true,
    startsAt: "2026-09-15",
    endsAt: "2026-11-30",
    location: "Онлайн",
    url: "https://events.unidoka.com",
    tags: ["соревнование", "BI"],
    prize: "1 000 000 ₽",
  },
  {
    id: "un-riscv-2026",
    title: "RISC-V Конкурс 2026",
    description: "Задачи на плате MIK32: embedded, RISC-V, RTOS.",
    source: "unidoka",
    organizer: "Унидока",
    type: "IT",
    country: "Россия",
    ageMin: 16,
    registrationOpen: true,
    startsAt: "2026-08-01",
    endsAt: "2026-12-20",
    location: "Онлайн",
    url: "https://events.unidoka.com",
    tags: ["hardware", "RISC-V"],
    prize: "до 49 999 ₽",
  },
  {
    id: "rov-design-jam-2026",
    title: "Rovno.dev Design Jam",
    description: "48-часовой интенсив по продукт-дизайну с менторами из индустрии.",
    source: "rovno",
    organizer: "Rovno.dev",
    type: "Design",
    country: "Россия",
    ageMin: 16,
    ageMax: 35,
    registrationOpen: true,
    startsAt: "2026-10-10",
    endsAt: "2026-10-12",
    location: "Москва",
    url: "https://rovno.dev",
    tags: ["design", "интенсив"],
  },
  {
    id: "rov-art-night-2026",
    title: "Rovno Art Night",
    description: "Вечер современного искусства и цифрового дизайна с открытым микрофоном.",
    source: "rovno",
    organizer: "Rovno.dev",
    type: "Art",
    country: "Россия",
    ageMin: 18,
    registrationOpen: true,
    startsAt: "2026-10-25",
    endsAt: "2026-10-25",
    location: "Санкт-Петербург",
    tags: ["art", "митап"],
  },
  {
    id: "un-sport-cup-2027",
    title: "Unidoka Sport Cup",
    description: "Корпоративный турнир: футбол, волейбол, шахматы.",
    source: "unidoka",
    organizer: "Унидока",
    type: "Sport",
    country: "Россия",
    ageMin: 18,
    registrationOpen: false,
    startsAt: "2027-05-15",
    endsAt: "2027-05-16",
    location: "Казань",
    tags: ["спорт"],
  },
  {
    id: "rov-chill-meetup-2027",
    title: "Rovno Chill Meetup",
    description: "Неформальная встреча комьюнити: кофе, разговоры, нетворкинг.",
    source: "rovno",
    organizer: "Rovno.dev",
    type: "Chill",
    country: "Россия",
    ageMin: 16,
    registrationOpen: true,
    startsAt: "2027-01-20",
    location: "Москва",
    tags: ["митап"],
  },
  {
    id: "rc-construction-forum-2027",
    title: "Форум по строительству и урбанистике",
    description: "Инфраструктура, ЖКХ, умные города.",
    source: "roscongress",
    organizer: "Росконгресс",
    type: "Construction",
    country: "Россия",
    ageMin: 18,
    registrationOpen: false,
    startsAt: "2027-03-10",
    endsAt: "2027-03-12",
    location: "Москва",
    tags: ["строительство", "урбанистика"],
  },
];
