
Project main_db {
  database_type: 'PostgreSQL'
  Note: 'Main service db'
}

Enum user_role {
  client, // can only get notifications
  user, // can make user articles, have and profile (in future)
  admin, // user + can make crud of all users (except admins), articles, projects, etc.
  root, // admin + can make crud of all users
}

Enum user_status { 
  pending_verification
  verificated
  blocked
}

Table users {
  id bigint [pk, increment]
  username varchar [note: 'Slug-based string ID like niyazgim']
  name varchar
  surname varchar
  email varchar [unique]
  phone varchar [unique]
  password varchar [not null]
  description text [note: 'Short bio/description']
  avatar_url varchar
  user_role user_role [default: 'user']
  user_status user_status [default: 'pending_verification']
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
}