export * from "./logotypes/chrome-logo-icon"
export * from "./logotypes/telegram-logo-icon"
export * from "./logotypes/telegram-logo-mono-icon"
export * from "./logotypes/pinterest-logo-mono-icon"
export * from "./logotypes/dprofile-logo-mono-icon"
export * from "./logotypes/vk-logo-mono-icon"
export * from "./logotypes/github-logo-mono-icon"
export * from "./icon"